export const testGridPlayer = [
  [
    {
      col: 0,
      row: 0,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 1,
      row: 0,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 2,
      row: 0,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 3,
      row: 0,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 4,
      row: 0,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 5,
      row: 0,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 6,
      row: 0,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 7,
      row: 0,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 8,
      row: 0,
      isFilled: true,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "battleship",
      shipId: 2,
      direction: "up",
    },
    {
      col: 9,
      row: 0,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
  ],
  [
    {
      col: 0,
      row: 1,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 1,
      row: 1,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 2,
      row: 1,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 3,
      row: 1,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 4,
      row: 1,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 5,
      row: 1,
      isFilled: true,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "destroyer",
      shipId: 5,
      direction: "left",
    },
    {
      col: 6,
      row: 1,
      isFilled: true,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "destroyer",
      shipId: 5,
      direction: "left",
    },
    {
      col: 7,
      row: 1,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 8,
      row: 1,
      isFilled: true,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "battleship",
      shipId: 2,
      direction: "up",
    },
    {
      col: 9,
      row: 1,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
  ],
  [
    {
      col: 0,
      row: 2,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 1,
      row: 2,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 2,
      row: 2,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 3,
      row: 2,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 4,
      row: 2,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 5,
      row: 2,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 6,
      row: 2,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 7,
      row: 2,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 8,
      row: 2,
      isFilled: true,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "battleship",
      shipId: 2,
      direction: "down",
    },
    {
      col: 9,
      row: 2,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
  ],
  [
    {
      col: 0,
      row: 3,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 1,
      row: 3,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 2,
      row: 3,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 3,
      row: 3,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 4,
      row: 3,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 5,
      row: 3,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 6,
      row: 3,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 7,
      row: 3,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 8,
      row: 3,
      isFilled: true,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "destroyer",
      shipId: 4,
      direction: "up",
    },
    {
      col: 9,
      row: 3,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
  ],
  [
    {
      col: 0,
      row: 4,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 1,
      row: 4,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 2,
      row: 4,
      isFilled: true,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "destroyer",
      shipId: 3,
      direction: "right",
    },
    {
      col: 3,
      row: 4,
      isFilled: true,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "destroyer",
      shipId: 3,
      direction: "right",
    },
    {
      col: 4,
      row: 4,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 5,
      row: 4,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 6,
      row: 4,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 7,
      row: 4,
      isFilled: true,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "submarine",
      shipId: 9,
      direction: "up",
    },
    {
      col: 8,
      row: 4,
      isFilled: true,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "destroyer",
      shipId: 4,
      direction: "up",
    },
    {
      col: 9,
      row: 4,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
  ],
  [
    {
      col: 0,
      row: 5,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 1,
      row: 5,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 2,
      row: 5,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 3,
      row: 5,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 4,
      row: 5,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 5,
      row: 5,
      isFilled: true,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "battleship",
      shipId: 1,
      direction: "right",
    },
    {
      col: 6,
      row: 5,
      isFilled: true,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "battleship",
      shipId: 1,
      direction: "right",
    },
    {
      col: 7,
      row: 5,
      isFilled: true,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "battleship",
      shipId: 1,
      direction: "right",
    },
    {
      col: 8,
      row: 5,
      isFilled: true,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "submarine",
      shipId: 7,
      direction: "down",
    },
    {
      col: 9,
      row: 5,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
  ],
  [
    {
      col: 0,
      row: 6,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 1,
      row: 6,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 2,
      row: 6,
      isFilled: true,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "carrier",
      shipId: 0,
      direction: "up",
    },
    {
      col: 3,
      row: 6,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 4,
      row: 6,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 5,
      row: 6,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 6,
      row: 6,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 7,
      row: 6,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 8,
      row: 6,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 9,
      row: 6,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
  ],
  [
    {
      col: 0,
      row: 7,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 1,
      row: 7,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 2,
      row: 7,
      isFilled: true,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "carrier",
      shipId: 0,
      direction: "down",
    },
    {
      col: 3,
      row: 7,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 4,
      row: 7,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 5,
      row: 7,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 6,
      row: 7,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 7,
      row: 7,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 8,
      row: 7,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 9,
      row: 7,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
  ],
  [
    {
      col: 0,
      row: 8,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 1,
      row: 8,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 2,
      row: 8,
      isFilled: true,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "carrier",
      shipId: 0,
      direction: "down",
    },
    {
      col: 3,
      row: 8,
      isFilled: true,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "submarine",
      shipId: 8,
      direction: "up",
    },
    {
      col: 4,
      row: 8,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 5,
      row: 8,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 6,
      row: 8,
      isFilled: true,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "submarine",
      shipId: 6,
      direction: "left",
    },
    {
      col: 7,
      row: 8,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 8,
      row: 8,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 9,
      row: 8,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
  ],
  [
    {
      col: 0,
      row: 9,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 1,
      row: 9,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 2,
      row: 9,
      isFilled: true,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "carrier",
      shipId: 0,
      direction: "down",
    },
    {
      col: 3,
      row: 9,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 4,
      row: 9,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 5,
      row: 9,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 6,
      row: 9,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 7,
      row: 9,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 8,
      row: 9,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
    {
      col: 9,
      row: 9,
      isFilled: false,
      isHit: false,
      missed: false,
      isPlayersBoard: false,
      shipType: "",
      shipId: 0,
      direction: "",
    },
  ],
];
